######################################################################
# Automatically generated by qmake (3.0) Mon Feb 16 16:21:23 2015
######################################################################

QT += opengl widgets testlib
CONFIG += testcase
TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

# Input
HEADERS += ../point.h \
           ../functor.h
SOURCES += tests.cpp \
           ../point.cpp \
           ../functor.cpp
